# Generated by Django 4.2.4 on 2023-08-30 02:37

import core.models
import cuid2.generator
from django.db import migrations, models
import django_choices_field.fields
import employee.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    core.models.CuidField(
                        default=cuid2.generator.Cuid.generate,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                (
                    "area",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("biz_dev", "Business Development"),
                            ("data", "Data Science"),
                            ("engineering", "Engineering"),
                            ("finance", "Finance"),
                            ("hr", "Human Resources"),
                            ("inventory", "Inventory Management"),
                            ("marketing", "Marketing"),
                            ("supply_chain", "Supply Chain Management"),
                            ("support", "Customer Support"),
                        ],
                        choices_enum=employee.models.Team.AreaEnum,
                        max_length=12,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    core.models.CuidField(
                        default=cuid2.generator.Cuid.generate,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "teams",
                    models.ManyToManyField(
                        related_name="employees", to="employee.team"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
